export const GET_CATEGORY_JOKE = "GET_CATEGORY_JOKE";
export const GET_CATEGORY_JOKE_ERROR = "GET_CATEGORY_JOKE_ERROR";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const CATEGORIES_ERROR = "CATEGORIES_ERROR";
export const GET_RANDOM_JOKE = "GET_RANDOM_JOKE";
export const RANDOM_JOKE_ERROR = "RANDOM_JOKE_ERROR";
